# Generated by Django 3.2.9 on 2021-11-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211103_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first',
        ),
    ]
