# Generated by Django 3.2.9 on 2021-11-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_countrylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrylist',
            name='country_name',
            field=models.CharField(max_length=100),
        ),
    ]
