# Generated by Django 3.2.9 on 2021-11-19 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_countrylist_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.countrylist'),
            preserve_default=False,
        ),
    ]
