# Generated by Django 4.1 on 2022-08-10 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 10, 20, 47, 16, 253005)),
        ),
        migrations.AlterField(
            model_name='userrolemodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 10, 20, 47, 16, 255010)),
        ),
    ]
