# Generated by Django 4.1 on 2022-08-10 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_created_on_alter_userrolemodel_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRolePrevilegeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('menu_code', models.CharField(max_length=100)),
                ('create_rights', models.BooleanField()),
                ('retrieve_rights', models.BooleanField()),
                ('update_rights', models.BooleanField()),
                ('delete_rights', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 10, 21, 27, 54, 618614)),
        ),
        migrations.AlterField(
            model_name='userrolemodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 10, 21, 27, 54, 620609)),
        ),
    ]
