# Generated by Django 4.1 on 2022-08-11 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userroleprevilegemodel_alter_user_created_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_root', models.BooleanField(default=False)),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_link', models.CharField(blank=True, max_length=500, null=True)),
                ('menu_icon', models.CharField(blank=True, max_length=250, null=True)),
                ('is_submenu', models.BooleanField(default=False)),
                ('submenu_name', models.CharField(blank=True, max_length=100, null=True)),
                ('submenu_link', models.CharField(blank=True, max_length=500, null=True)),
                ('submenu_icon', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 10, 33, 13, 482545)),
        ),
        migrations.AlterField(
            model_name='userrolemodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 10, 33, 13, 485538)),
        ),
    ]
