# Generated by Django 4.1 on 2022-08-11 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_menulistmodel_alter_user_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 10, 46, 56, 62047)),
        ),
        migrations.AlterField(
            model_name='userrolemodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 10, 46, 56, 63995)),
        ),
    ]
