# Generated by Django 4.1 on 2022-08-11 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_created_on_alter_userrolemodel_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 13, 51, 44, 695630)),
        ),
        migrations.AlterField(
            model_name='userrolemodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 13, 51, 44, 697624)),
        ),
    ]
