# Generated by Django 3.2.9 on 2021-11-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=250, unique=True)),
                ('channel_description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
