# Generated by Django 3.2.9 on 2021-11-09 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(max_length=50, unique=True)),
                ('stream_file', models.FileField(upload_to='stream')),
                ('stream_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.channels')),
            ],
        ),
    ]
