# Generated by Django 3.2.9 on 2021-11-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streams',
            name='stream_cheers',
            field=models.IntegerField(default=0),
        ),
    ]
