# Generated by Django 3.2.9 on 2021-11-18 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_streams_stream_cheers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.TextField()),
                ('stream_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.streams')),
            ],
        ),
    ]
