# Generated by Django 3.2.9 on 2021-11-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0003_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Feedback',
            new_name='feedback',
        ),
    ]
