# Generated by Django 3.2.9 on 2021-11-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_feedback_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='streams',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
