# Generated by Django 3.2.3 on 2021-06-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levellistmodel',
            options={'ordering': ('level_name',)},
        ),
    ]
