# Generated by Django 4.1 on 2022-08-11 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcenter', '0003_itemcategoriesmodel_delete_itemcategories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('item_image', models.ImageField(null=True, upload_to='items_image')),
                ('item_category', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2022, 8, 11, 15, 16, 47, 502943))),
                ('last_updated_on', models.DateTimeField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='costcentermodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 15, 16, 47, 501944)),
        ),
        migrations.AlterField(
            model_name='itemcategoriesmodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 15, 16, 47, 501944)),
        ),
    ]
