# Generated by Django 4.1 on 2022-08-11 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcenter', '0004_itemsmodel_alter_costcentermodel_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsmodel',
            name='item_rate',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='costcentermodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 19, 56, 2, 970670)),
        ),
        migrations.AlterField(
            model_name='itemcategoriesmodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 19, 56, 2, 971667)),
        ),
        migrations.AlterField(
            model_name='itemsmodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 19, 56, 2, 971667)),
        ),
    ]
