# Generated by Django 4.1 on 2022-08-11 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcenter', '0005_itemsmodel_item_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('table_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2022, 8, 11, 20, 2, 17, 155912))),
                ('last_updated_on', models.DateTimeField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='costcentermodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 20, 2, 17, 154870)),
        ),
        migrations.AlterField(
            model_name='itemcategoriesmodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 20, 2, 17, 154870)),
        ),
        migrations.AlterField(
            model_name='itemsmodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 20, 2, 17, 155912)),
        ),
    ]
