# Generated by Django 4.1 on 2022-08-11 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcenter', '0006_tablemodel_alter_costcentermodel_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablemodel',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='costcentermodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 20, 30, 17, 314207)),
        ),
        migrations.AlterField(
            model_name='itemcategoriesmodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 20, 30, 17, 314207)),
        ),
        migrations.AlterField(
            model_name='itemsmodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 20, 30, 17, 315205)),
        ),
        migrations.AlterField(
            model_name='tablemodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 20, 30, 17, 315205)),
        ),
    ]
