# Generated by Django 4.1 on 2022-08-11 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcenter', '0007_tablemodel_is_occupied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcentermodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 20, 35, 39, 55644)),
        ),
        migrations.AlterField(
            model_name='itemcategoriesmodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 20, 35, 39, 56641)),
        ),
        migrations.AlterField(
            model_name='itemsmodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 20, 35, 39, 56641)),
        ),
        migrations.AlterField(
            model_name='tablemodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 20, 35, 39, 57639)),
        ),
    ]
