# Generated by Django 4.1 on 2022-08-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_masterid', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=100)),
                ('item_quantity', models.IntegerField()),
                ('item_rate', models.IntegerField()),
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='order_Masterid',
            new_name='order_masterid',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='table_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
