# Generated by Django 3.2.3 on 2021-06-03 12:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('level', '0002_alter_levellistmodel_options'),
        ('position', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_firstname', models.CharField(max_length=15)),
                ('emp_middlename', models.CharField(blank=True, max_length=15)),
                ('emp_lastname', models.CharField(max_length=15)),
                ('emp_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('emp_DOB', models.DateField()),
                ('emp_contact_number', models.CharField(max_length=15)),
                ('emp_mail', models.EmailField(max_length=254)),
                ('emp_address', models.CharField(max_length=50)),
                ('emp_image', models.ImageField(null=True, upload_to='employee_images')),
                ('emp_image_binary', models.BinaryField(null=True)),
                ('emp_document', models.FileField(upload_to='documents')),
                ('emp_registered_date', models.DateField(default=datetime.date(2021, 6, 3))),
                ('emp_joining_date', models.DateField()),
                ('emp_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.departmentlistmodel')),
                ('emp_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='level.levellistmodel')),
                ('emp_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='position.positionlistmodel')),
            ],
            options={
                'ordering': ('emp_firstname',),
            },
        ),
    ]
