# Generated by Django 3.2.3 on 2021-06-10 16:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelistmodel',
            name='emp_registered_date',
            field=models.DateField(default=datetime.date(2021, 6, 10)),
        ),
        migrations.CreateModel(
            name='EmployeeLogmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(blank=True, choices=[('I', 'Check-in'), ('O', 'Check-Out')], max_length=1, null=True)),
                ('check_in_datetime', models.DateTimeField()),
                ('check_out_datetime', models.DateTimeField()),
                ('emp_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employeelistmodel')),
            ],
        ),
    ]
