# Generated by Django 3.2.3 on 2021-06-15 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210610_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelistmodel',
            name='emp_registered_date',
            field=models.DateField(default=datetime.date(2021, 6, 15)),
        ),
        migrations.AlterField(
            model_name='employeelogmodel',
            name='check_out_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
