# Generated by Django 3.2.3 on 2021-10-29 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210615_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelistmodel',
            name='emp_registered_date',
            field=models.DateField(default=datetime.date(2021, 10, 29)),
        ),
    ]
